---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/cnruby/concourse-tutorial.git
      branch: develop

jobs:
  - name: job-hallo-apache
    public: true
    plan:
      - get: resource-tutorial
      - task: hallo-apache
        file: resource-tutorial/tutorials/basic/task-hello-world/task_apache.yml

# fly -t tutorial set-pipeline -c pipeline-apache.yml -p hallo-apache